import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.6.20"
    application
    id("org.graalvm.buildtools.native") version "0.9.11"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

group = "com.code0x378"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-simple:1.7.31")
    implementation("io.javalin:javalin:4.5.0")
    testImplementation(kotlin("test"))
}

graalvmNative {
    binaries {
        named("main") {
            imageName.set("gvm-app")
            configurationFileDirectories.from(file("gvm-config"))
            useFatJar.set(true)
            // debug.set(true)
            // verbose.set(true)

            // Not used as we specify the config dir, with even more info, that is automatically generated by the agent (see readme)
            // buildArgs.add("-H:IncludeResourceBundles=javax.servlet.LocalStrings")
            // buildArgs.add("-H:IncludeResourceBundles=javax.servlet.http.LocalStrings")
            // buildArgs.add("-H:ReflectionConfigurationFiles=../../../reflection.json")
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClass.set("MainKt")
}
